### ISSUE TITLE
Error in Dimation of quantum gate

### ISSUE THREAD

**Issue by saphir100** [TravisCao/L-QLSTM#1]
Hi,
I try to run xx-qlstm model with 'x_3d_period1' data, but i have this error "RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x16 and 4x1)"

**Comment by TravisCao** [comment]
Hi, can you give me the exact steps to reproduce your error?

**Comment by saphir100** [comment]
> Hi, can you give me the exact steps to reproduce your error?

In the file xx_qlstm.py, exactly at line 87 or 92  where the code is: "f_t = torch.sigmoid(self.clayer_out(f_t_vqc))." /"f_t = torch.sigmoid(self.clayer_out_forget(f_t_vqc))".
The complete console content has been uploaded in the file "ErrInConsole.txt," which contains the relevant errors.
[ErrInConsole.txt](https://github.com/user-attachments/files/17253658/ErrInConsole.txt)

**Comment by TravisCao** [comment]
Please give me the terminal command you executed so that I can reproduce your error. I can't see the command From your console output:(
For example,
```bash
python src/train.py --batch_size 16 --model_name xx-QLSTM --devices 16 --accelerator cpu --n_qubits 4
```

**Comment by saphir100** [comment]
> Please give me the terminal command you executed so that I can reproduce your error. I can't see the command From your console output:( For example,
> 
> ```shell
> python src/train.py --batch_size 16 --model_name xx-QLSTM --devices 16 --accelerator cpu --n_qubits 4
> ```

I executed it with the same command you posted on Git. I have also included the command in this file errxxQlstm.txt. Please check it.
[Uploading errxxQLSTM.txt…]()

**Comment by saphir100** [comment]
I executed it with the same command you posted on Git. I have also included the command in this file errxxQlstm.txt. Please check it.
[errxxQLSTM.txt](https://github.com/user-attachments/files/17271314/errxxQLSTM.txt)

**Comment by TravisCao** [comment]
I can run this without problems... Maybe you can start with running it without multi-processing or distributed training, i.e., `--device 1` and then give me the error info. 

Also, from your error info, I think the key is to check the dimension of data when feeding in & out the QLSTM and linear network.

**Comment by saphir100** [comment]
It can almost be said that the problem was with the device 16, and to some extent, the issue has been resolved, though not completely. Anyway, thank you for your help, and if you could assist in fully resolving the error, I would appreciate it. I also have a question: I want to use your model with a time series dataset that has one column for time, 60 columns for features, and one column for the target. I would be grateful if you could guide me on what changes I need to make so that I can input this dataset into the model and get an output. Thank you!

[outConsole.txt](https://github.com/user-attachments/files/17278818/outConsole.txt)

**Comment by TravisCao** [comment]
I think the error is because pytorch-lightning has bad multi-processing support on the Windows platform. So when you use multi-core to run it. The problem appears. 

To use it on your dataset, you need to change the input size and output size. Input size should be changed to 60 + 1, output size should be changed to 1.
